# Default application configuration that all configurations inherit from.
# Check options: https://github.com/brigade/scss-lint/blob/master/config/default.yml

scss_files: "design/source/sass/**/*.scss"

# Default severity of all linters.
severity: error

linters:
  HexLength:
    enabled: true
    style: long # or 'long'

  HexNotation:
    enabled: true
    style: uppercase # or 'uppercase'

  Indentation:
    width: 1
    character: tab

  LeadingZero:
    enabled: true
    style: include_zero
